name: Validate
on:
  pull_request:
    paths: ["**.bs"]
jobs:
  main:
    name: Validate Spec
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: w3c/spec-prod@v2
        with:
          TOOLCHAIN: bikeshed
          SOURCE: spec.bs
          BUILD_FAIL_ON: warning
